openapi: '3.0.0'

info:
  title: AIRR Data Commons API Germline Extension
  version: 1.0.0
  contact:
    name: AIRR Community
    url: 'http://www.airr-community.org/'
    email: join@airr-community.org
  description: >
    Extension API for Major Version 1 of the AIRR Data Commons API
    for query and download of germline sets and gene descriptions
  license:
    name: Creative Commons Attribution 4.0 International
    url: https://creativecommons.org/licenses/by/4.0/

servers:
  - url: https://vdjserver.org/airr/v1
    description: VDJServer ADC API Extension for Asynchronous Queries
    variables:
      basePath:
        default: /airr/v1

components:
  schemas:
    # Info object
    info_object:
      type: object
      description: Provides information about the API response
      properties:
        title:
          type: string
        version:
          type: string
        description:
          type: string
        contact: 
          type: object
          properties:
            name:
              type: string
            url:
              type: string
            email:
              type: string
        license:
          type: object
          properties:
            name:
              type: string
            url:
              type: string

    # POST query request
    query_object:
      description: Query filter and associated parameters for POST end points
      type: object
      properties:
        filters:
          type: object
        format:
          type: string
          default: json
          enum:
            - json
        fields:
          type: array
          items:
            type: string
        size:
          type: integer
        from:
          type: integer
        include_fields:
          type: string
          enum:
            - miairr
            - airr-core
            - airr-schema

    # list of germline sets
    germline_set_list:
      type: array
      items:
        $ref: 'https://raw.githubusercontent.com/airr-community/airr-standards/germline/specs/airr-schema-openapi3.yaml#/GermlineSet'

    # list of facets
    facet_list:
      type: array
      items:
        type: object
        properties:
          count:
            type: integer
          
    # list of gene descriptions
    gene_description_list:
      type: array
      items:
        $ref: 'https://raw.githubusercontent.com/airr-community/airr-standards/germline/specs/airr-schema-openapi3.yaml#/GeneDescription'

    # The response object /germline endpoint
    germline_set_response:
      type: object
      properties:
        Info:
          $ref: '#/components/schemas/info_object'
        GermlineSet:
          $ref: '#/components/schemas/germline_set_list'
        Facet:
          $ref: '#/components/schemas/facet_list'

    # The response object /gene endpoint
    gene_description_response:
      type: object
      properties:
        Info:
          $ref: '#/components/schemas/info_object'
        GeneDescription:
          $ref: '#/components/schemas/gene_description_list'
        Facet:
          $ref: '#/components/schemas/facet_list'

    # error response
    error_response:
      type: object
      properties:
        message:
          type: string
          description: Detail about the error

paths:
  /germline/{germline_set_id}:
    get:
      description: >
        Returns a germline set based upon its identifier.
      operationId: get_germline_set
      tags:
        - germline
      parameters:
        - name: germline_set_id
          in: path
          description: ID of germline set to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: |
            A successful call returns the germline set data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/germline_set_response'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'

  /germline:
    post:
      description: >
        This query service returns germline sets.
      operationId: query_germline_sets
      tags:
        - germline
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/query_object'
      responses:
        '200':
          description: |
            A successful call returns the germline set data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/germline_set_response'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'

  /gene/{gene_description_id}:
    get:
      description: >
        Returns a gene description based upon its identifier.
      operationId: get_gene_description
      tags:
        - germline
      parameters:
        - name: gene_description_id
          in: path
          description: ID of gene description to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: >
            A successful call returns the gene description data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gene_description_response'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'

  /gene:
    post:
      description: >
        This query service returns gene description data.
      operationId: query_gene_descriptions
      tags:
        - germline
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/query_object'
      responses:
        '200':
          description: >
            A successful call returns the gene description data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gene_description_response'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'

